C = gcc
CXX = g++
ROOT := $(shell pwd)
SUBDIR := capi \
		  configs \
		  http \
		  libocispec \
		  main \
		  net \
		  registry \
		  storage \
		  utils
OBJ_DIR := $(ROOT)/obj
BIN_DIR := $(ROOT)/bin
BIN := docker-mini
C_LIB = net/network.c net/nl.c http/http.c \
		libocispec/json_common.c \
		libocispec/defs.c \
		libocispec/read-file.c \
		libocispec/container_config.c \
		libocispec/container_inspect.c \
		libocispec/container_network_settings.c \
		libocispec/docker_image_history.c \
		libocispec/docker_image_rootfs.c \
		libocispec/docker_image_config_v2.c \
		libocispec/docker_types_mount_point.c \
		libocispec/registry_auths.c \
		libocispec/registry_manifest_list.c \
		libocispec/registry_manifest_schema2.c \
		libocispec/registry_manifest_schema1.c \
		libocispec/registry_token.c \
		libocispec/storage_spec.c \
		libocispec/storage_storage.c \
		libocispec/storage_entry.c \
		libocispec/storage_layer.c \
		libocispec/storage_rootfs.c \
		libocispec/storage_mount_point.c \
		libocispec/cni_anno_port_mappings.c \
		libocispec/cni_inner_port_mapping.c \
		libocispec/network_port_binding.c \
		libocispec/oci_image_defs_descriptor.c \
		libocispec/oci_image_index.c \
		libocispec/oci_image_manifest.c \
		libocispec/oci_image_content_descriptor.c \
		libocispec/oci_image_spec.c \
		libocispec/configs_constants.c \
		utils/utils.c \
		utils/sha256.c \
		utils/timestamp.c \
		utils/archive.c \
		utils/fs.c \
		registry/registry.c \
		storage/storage.c \
		storage/layer.c \
		storage/driver.c \
		storage/project_quota.c \
		storage/rootfs.c \
		capi/image_api.c \
		capi/container_api.c \
		configs/config.c 

C_LINK = network.o nl.o http.o utils.o sha256.o timestamp.o \
		 json_common.o \
		 defs.o \
		 read-file.o \
		 container_config.o \
		 container_inspect.o \
		 container_network_settings.o \
		 docker_image_history.o \
		 docker_image_rootfs.o \
		 docker_image_config_v2.o \
		 docker_types_mount_point.o \
		 registry_auths.o \
		 registry_manifest_list.o \
		 registry_manifest_schema2.o \
		 registry_manifest_schema1.o \
		 registry_token.o \
		 storage_spec.o \
		 storage_storage.o \
		 storage_entry.o \
		 storage_layer.o \
		 storage_rootfs.o \
		 storage_mount_point.o \
		 cni_anno_port_mappings.o \
		 cni_inner_port_mapping.o \
		 network_port_binding.o \
		 oci_image_defs_descriptor.o \
		 oci_image_index.o \
		 oci_image_manifest.o \
		 oci_image_content_descriptor.o \
		 oci_image_spec.o \
		 configs_constants.o \
		 archive.o \
		 fs.o \
		 registry.o \
		 storage.o \
		 layer.o \
		 driver.o \
		 project_quota.o \
		 rootfs.o \
		 image_api.o \
		 container_api.o \
		 config.o
MAIN = main/main.cpp main/docker.cc
LD = -std=c++11
OUT = docker-run

all:
	make container
container:
	$(C) -c $(C_LIB) 
	$(CXX) $(LD) -o $(OUT) $(MAIN) $(C_LINK) -lcurl -lhttp_parser -lyajl -lcrypto -lssl -lm -lz -I/usr/local/include -L/usr/local/lib -larchive 
clean:
	rm *.o $(OUT)
