all: $(OBJ_DIR)/json_common.o \
     $(OBJ_DIR)/defs.o \
     $(OBJ_DIR)/read-file.o \
     $(OBJ_DIR)/container_config.o \
     $(OBJ_DIR)/container_inspect.o \
     $(OBJ_DIR)/container_network_settings.o \
     $(OBJ_DIR)/docker_image_history.o \
     $(OBJ_DIR)/docker_image_rootfs.o \
     $(OBJ_DIR)/docker_image_config_v2.o \
     $(OBJ_DIR)/docker_types_mount_point.o \
     $(OBJ_DIR)/registry_auths.o \
     $(OBJ_DIR)/registry_manifest_list.o \
     $(OBJ_DIR)/registry_manifest_schema2.o \
     $(OBJ_DIR)/registry_manifest_schema1.o \
     $(OBJ_DIR)/registry_token.o \
     $(OBJ_DIR)/storage_spec.o \
     $(OBJ_DIR)/storage_storage.o \
     $(OBJ_DIR)/storage_entry.o \
	 $(OBJ_DIR)/storage_layer.o \
	 $(OBJ_DIR)/storage_rootfs.o \
	 $(OBJ_DIR)/storage_mount_point.o \
	 $(OBJ_DIR)/cni_anno_port_mappings.o \
	 $(OBJ_DIR)/cni_inner_port_mapping.o \
	 $(OBJ_DIR)/network_port_binding.o \
	 $(OBJ_DIR)/oci_image_defs_descriptor.o \
	 $(OBJ_DIR)/oci_image_index.o \
	 $(OBJ_DIR)/oci_image_manifest.o \
	 $(OBJ_DIR)/oci_image_content_descriptor.o \
	 $(OBJ_DIR)/oci_image_spec.o \
	 $(OBJ_DIR)/configs_constants.o

$(OBJ_DIR)/json_common.o: json_common.c
	$(C) -c $< -o $@
$(OBJ_DIR)/defs.o: defs.c
	$(C) -c $< -o $@
$(OBJ_DIR)/read-file.o: read-file.c
	$(C) -c $< -o $@
$(OBJ_DIR)/container_config.o: container_config.c
	$(C) -c $< -o $@
$(OBJ_DIR)/container_inspect.o: container_inspect.c
	$(C) -c $< -o $@
$(OBJ_DIR)/container_network_settings.o: container_network_settings.c
	$(C) -c $< -o $@
$(OBJ_DIR)/docker_image_history.o: docker_image_history.c
	$(C) -c $< -o $@
$(OBJ_DIR)/docker_image_rootfs.o: docker_image_rootfs.c
	$(C) -c $< -o $@
$(OBJ_DIR)/docker_image_config_v2.o: docker_image_config_v2.c
	$(C) -c $< -o $@
$(OBJ_DIR)/docker_types_mount_point.o: docker_types_mount_point.c
	$(C) -c $< -o $@
$(OBJ_DIR)/registry_auths.o: registry_auths.c
	$(C) -c $< -o $@
$(OBJ_DIR)/registry_manifest_list.o: registry_manifest_list.c
	$(C) -c $< -o $@
$(OBJ_DIR)/registry_manifest_schema2.o: registry_manifest_schema2.c
	$(C) -c $< -o $@
$(OBJ_DIR)/registry_manifest_schema1.o: registry_manifest_schema1.c
	$(C) -c $< -o $@
$(OBJ_DIR)/registry_token.o: registry_token.c
	$(C) -c $< -o $@
$(OBJ_DIR)/storage_spec.o: storage_spec.c
	$(C) -c $< -o $@
$(OBJ_DIR)/storage_storage.o: storage_storage.c
	$(C) -c $< -o $@
$(OBJ_DIR)/storage_entry.o: storage_entry.c
	$(C) -c $< -o $@
$(OBJ_DIR)/storage_layer.o: storage_layer.c
	$(C) -c $< -o $@
$(OBJ_DIR)/storage_rootfs.o: storage_rootfs.c
	$(C) -c $< -o $@
$(OBJ_DIR)/storage_mount_point.o: storage_mount_point.c
	$(C) -c $< -o $@
$(OBJ_DIR)/cni_anno_port_mappings.o: cni_anno_port_mappings.c
	$(C) -c $< -o $@
$(OBJ_DIR)/cni_inner_port_mapping.o: cni_inner_port_mapping.c
	$(C) -c $< -o $@
$(OBJ_DIR)/network_port_binding.o: network_port_binding.c
	$(C) -c $< -o $@
$(OBJ_DIR)/oci_image_defs_descriptor.o: oci_image_defs_descriptor.c
	$(C) -c $< -o $@
$(OBJ_DIR)/oci_image_index.o: oci_image_index.c
	$(C) -c $< -o $@
$(OBJ_DIR)/oci_image_manifest.o: oci_image_manifest.c
	$(C) -c $< -o $@ -g
$(OBJ_DIR)/oci_image_content_descriptor.o: oci_image_content_descriptor.c
	$(C) -c $< -o $@
$(OBJ_DIR)/oci_image_spec.o: oci_image_spec.c
	$(C) -c $< -o $@
$(OBJ_DIR)/configs_constants.o: configs_constants.c
	$(C) -c $< -o $@
