// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: image.proto
#ifndef GRPC_image_2eproto__INCLUDED
#define GRPC_image_2eproto__INCLUDED

#include "image.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace image {

class ImageService final {
 public:
  static constexpr char const* service_full_name() {
    return "image.ImageService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status PullImage(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::image::PullImageReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::PullImageReply>> AsyncPullImage(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::PullImageReply>>(AsyncPullImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::PullImageReply>> PrepareAsyncPullImage(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::PullImageReply>>(PrepareAsyncPullImageRaw(context, request, cq));
    }
    virtual ::grpc::Status RemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::image::RemoveImageReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::RemoveImageReply>> AsyncRemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::RemoveImageReply>>(AsyncRemoveImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::RemoveImageReply>> PrepareAsyncRemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::image::RemoveImageReply>>(PrepareAsyncRemoveImageRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void PullImage(::grpc::ClientContext* context, const ::image::PullImageRequest* request, ::image::PullImageReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void PullImage(::grpc::ClientContext* context, const ::image::PullImageRequest* request, ::image::PullImageReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest* request, ::image::RemoveImageReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest* request, ::image::RemoveImageReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image::PullImageReply>* AsyncPullImageRaw(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image::PullImageReply>* PrepareAsyncPullImageRaw(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image::RemoveImageReply>* AsyncRemoveImageRaw(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::image::RemoveImageReply>* PrepareAsyncRemoveImageRaw(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status PullImage(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::image::PullImageReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::PullImageReply>> AsyncPullImage(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::PullImageReply>>(AsyncPullImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::PullImageReply>> PrepareAsyncPullImage(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::PullImageReply>>(PrepareAsyncPullImageRaw(context, request, cq));
    }
    ::grpc::Status RemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::image::RemoveImageReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::RemoveImageReply>> AsyncRemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::RemoveImageReply>>(AsyncRemoveImageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::RemoveImageReply>> PrepareAsyncRemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::image::RemoveImageReply>>(PrepareAsyncRemoveImageRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void PullImage(::grpc::ClientContext* context, const ::image::PullImageRequest* request, ::image::PullImageReply* response, std::function<void(::grpc::Status)>) override;
      void PullImage(::grpc::ClientContext* context, const ::image::PullImageRequest* request, ::image::PullImageReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest* request, ::image::RemoveImageReply* response, std::function<void(::grpc::Status)>) override;
      void RemoveImage(::grpc::ClientContext* context, const ::image::RemoveImageRequest* request, ::image::RemoveImageReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::image::PullImageReply>* AsyncPullImageRaw(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::image::PullImageReply>* PrepareAsyncPullImageRaw(::grpc::ClientContext* context, const ::image::PullImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::image::RemoveImageReply>* AsyncRemoveImageRaw(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::image::RemoveImageReply>* PrepareAsyncRemoveImageRaw(::grpc::ClientContext* context, const ::image::RemoveImageRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_PullImage_;
    const ::grpc::internal::RpcMethod rpcmethod_RemoveImage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status PullImage(::grpc::ServerContext* context, const ::image::PullImageRequest* request, ::image::PullImageReply* response);
    virtual ::grpc::Status RemoveImage(::grpc::ServerContext* context, const ::image::RemoveImageRequest* request, ::image::RemoveImageReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_PullImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_PullImage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_PullImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullImage(::grpc::ServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPullImage(::grpc::ServerContext* context, ::image::PullImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::image::PullImageReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RemoveImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RemoveImage() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RemoveImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoveImage(::grpc::ServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoveImage(::grpc::ServerContext* context, ::image::RemoveImageRequest* request, ::grpc::ServerAsyncResponseWriter< ::image::RemoveImageReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_PullImage<WithAsyncMethod_RemoveImage<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_PullImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_PullImage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::image::PullImageRequest, ::image::PullImageReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::image::PullImageRequest* request, ::image::PullImageReply* response) { return this->PullImage(context, request, response); }));}
    void SetMessageAllocatorFor_PullImage(
        ::grpc::MessageAllocator< ::image::PullImageRequest, ::image::PullImageReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::image::PullImageRequest, ::image::PullImageReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_PullImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullImage(::grpc::ServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PullImage(
      ::grpc::CallbackServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RemoveImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RemoveImage() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::image::RemoveImageRequest, ::image::RemoveImageReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::image::RemoveImageRequest* request, ::image::RemoveImageReply* response) { return this->RemoveImage(context, request, response); }));}
    void SetMessageAllocatorFor_RemoveImage(
        ::grpc::MessageAllocator< ::image::RemoveImageRequest, ::image::RemoveImageReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::image::RemoveImageRequest, ::image::RemoveImageReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RemoveImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoveImage(::grpc::ServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RemoveImage(
      ::grpc::CallbackServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_PullImage<WithCallbackMethod_RemoveImage<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_PullImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_PullImage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_PullImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullImage(::grpc::ServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RemoveImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RemoveImage() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RemoveImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoveImage(::grpc::ServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_PullImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_PullImage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_PullImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullImage(::grpc::ServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPullImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RemoveImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RemoveImage() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RemoveImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoveImage(::grpc::ServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRemoveImage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_PullImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_PullImage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->PullImage(context, request, response); }));
    }
    ~WithRawCallbackMethod_PullImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status PullImage(::grpc::ServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* PullImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RemoveImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RemoveImage() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RemoveImage(context, request, response); }));
    }
    ~WithRawCallbackMethod_RemoveImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RemoveImage(::grpc::ServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RemoveImage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_PullImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_PullImage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::image::PullImageRequest, ::image::PullImageReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::image::PullImageRequest, ::image::PullImageReply>* streamer) {
                       return this->StreamedPullImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_PullImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status PullImage(::grpc::ServerContext* /*context*/, const ::image::PullImageRequest* /*request*/, ::image::PullImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPullImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::image::PullImageRequest,::image::PullImageReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RemoveImage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RemoveImage() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::image::RemoveImageRequest, ::image::RemoveImageReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::image::RemoveImageRequest, ::image::RemoveImageReply>* streamer) {
                       return this->StreamedRemoveImage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RemoveImage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RemoveImage(::grpc::ServerContext* /*context*/, const ::image::RemoveImageRequest* /*request*/, ::image::RemoveImageReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRemoveImage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::image::RemoveImageRequest,::image::RemoveImageReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_PullImage<WithStreamedUnaryMethod_RemoveImage<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_PullImage<WithStreamedUnaryMethod_RemoveImage<Service > > StreamedService;
};

}  // namespace image


#endif  // GRPC_image_2eproto__INCLUDED
