// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

#include "image.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace image {

inline constexpr RemoveImageRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : image_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        force_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RemoveImageRequest::RemoveImageRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RemoveImageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemoveImageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemoveImageRequestDefaultTypeInternal() {}
  union {
    RemoveImageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemoveImageRequestDefaultTypeInternal _RemoveImageRequest_default_instance_;

inline constexpr RemoveImageReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : errmsg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RemoveImageReply::RemoveImageReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RemoveImageReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemoveImageReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemoveImageReplyDefaultTypeInternal() {}
  union {
    RemoveImageReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemoveImageReplyDefaultTypeInternal _RemoveImageReply_default_instance_;

inline constexpr PullImageRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : image_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PullImageRequest::PullImageRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PullImageRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PullImageRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PullImageRequestDefaultTypeInternal() {}
  union {
    PullImageRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PullImageRequestDefaultTypeInternal _PullImageRequest_default_instance_;

inline constexpr PullImageReply::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : image_ref_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        errmsg_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PullImageReply::PullImageReply(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PullImageReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PullImageReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PullImageReplyDefaultTypeInternal() {}
  union {
    PullImageReply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PullImageReplyDefaultTypeInternal _PullImageReply_default_instance_;
}  // namespace image
static ::_pb::Metadata file_level_metadata_image_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_image_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_image_2eproto = nullptr;
const ::uint32_t TableStruct_image_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::image::PullImageRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::image::PullImageRequest, _impl_.image_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::image::PullImageReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::image::PullImageReply, _impl_.image_ref_),
    PROTOBUF_FIELD_OFFSET(::image::PullImageReply, _impl_.errmsg_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::image::RemoveImageRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::image::RemoveImageRequest, _impl_.image_),
    PROTOBUF_FIELD_OFFSET(::image::RemoveImageRequest, _impl_.force_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::image::RemoveImageReply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::image::RemoveImageReply, _impl_.errmsg_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::image::PullImageRequest)},
        {9, -1, -1, sizeof(::image::PullImageReply)},
        {19, -1, -1, sizeof(::image::RemoveImageRequest)},
        {29, -1, -1, sizeof(::image::RemoveImageReply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::image::_PullImageRequest_default_instance_._instance,
    &::image::_PullImageReply_default_instance_._instance,
    &::image::_RemoveImageRequest_default_instance_._instance,
    &::image::_RemoveImageReply_default_instance_._instance,
};
const char descriptor_table_protodef_image_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\013image.proto\022\005image\"!\n\020PullImageRequest"
    "\022\r\n\005image\030\001 \001(\t\"3\n\016PullImageReply\022\021\n\tima"
    "ge_ref\030\001 \001(\t\022\016\n\006errmsg\030\002 \001(\t\"2\n\022RemoveIm"
    "ageRequest\022\r\n\005image\030\001 \001(\t\022\r\n\005force\030\002 \001(\010"
    "\"\"\n\020RemoveImageReply\022\016\n\006errmsg\030\001 \001(\t2\222\001\n"
    "\014ImageService\022=\n\tPullImage\022\027.image.PullI"
    "mageRequest\032\025.image.PullImageReply\"\000\022C\n\013"
    "RemoveImage\022\031.image.RemoveImageRequest\032\027"
    ".image.RemoveImageReply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_image_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_image_2eproto = {
    false,
    false,
    353,
    descriptor_table_protodef_image_2eproto,
    "image.proto",
    &descriptor_table_image_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_image_2eproto::offsets,
    file_level_metadata_image_2eproto,
    file_level_enum_descriptors_image_2eproto,
    file_level_service_descriptors_image_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_image_2eproto_getter() {
  return &descriptor_table_image_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_image_2eproto(&descriptor_table_image_2eproto);
namespace image {
// ===================================================================

class PullImageRequest::_Internal {
 public:
};

PullImageRequest::PullImageRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:image.PullImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE PullImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : image_(arena, from.image_),
        _cached_size_{0} {}

PullImageRequest::PullImageRequest(
    ::google::protobuf::Arena* arena,
    const PullImageRequest& from)
    : ::google::protobuf::Message(arena) {
  PullImageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:image.PullImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE PullImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : image_(arena),
        _cached_size_{0} {}

inline void PullImageRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PullImageRequest::~PullImageRequest() {
  // @@protoc_insertion_point(destructor:image.PullImageRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PullImageRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.image_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PullImageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:image.PullImageRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PullImageRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> PullImageRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PullImageRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string image = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PullImageRequest, _impl_.image_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string image = 1;
    {PROTOBUF_FIELD_OFFSET(PullImageRequest, _impl_.image_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\5\0\0\0\0\0\0"
    "image.PullImageRequest"
    "image"
  }},
};

::uint8_t* PullImageRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:image.PullImageRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string image = 1;
  if (!this->_internal_image().empty()) {
    const std::string& _s = this->_internal_image();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "image.PullImageRequest.image");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:image.PullImageRequest)
  return target;
}

::size_t PullImageRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:image.PullImageRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string image = 1;
  if (!this->_internal_image().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_image());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PullImageRequest::_class_data_ = {
    PullImageRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PullImageRequest::GetClassData() const {
  return &_class_data_;
}

void PullImageRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PullImageRequest*>(&to_msg);
  auto& from = static_cast<const PullImageRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:image.PullImageRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_image().empty()) {
    _this->_internal_set_image(from._internal_image());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PullImageRequest::CopyFrom(const PullImageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:image.PullImageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PullImageRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PullImageRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PullImageRequest::InternalSwap(PullImageRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_, &other->_impl_.image_, arena);
}

::google::protobuf::Metadata PullImageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_image_2eproto_getter, &descriptor_table_image_2eproto_once,
      file_level_metadata_image_2eproto[0]);
}
// ===================================================================

class PullImageReply::_Internal {
 public:
};

PullImageReply::PullImageReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:image.PullImageReply)
}
inline PROTOBUF_NDEBUG_INLINE PullImageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : image_ref_(arena, from.image_ref_),
        errmsg_(arena, from.errmsg_),
        _cached_size_{0} {}

PullImageReply::PullImageReply(
    ::google::protobuf::Arena* arena,
    const PullImageReply& from)
    : ::google::protobuf::Message(arena) {
  PullImageReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:image.PullImageReply)
}
inline PROTOBUF_NDEBUG_INLINE PullImageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : image_ref_(arena),
        errmsg_(arena),
        _cached_size_{0} {}

inline void PullImageReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PullImageReply::~PullImageReply() {
  // @@protoc_insertion_point(destructor:image.PullImageReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PullImageReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.image_ref_.Destroy();
  _impl_.errmsg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void PullImageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:image.PullImageReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_ref_.ClearToEmpty();
  _impl_.errmsg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PullImageReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 44, 2> PullImageReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PullImageReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string errmsg = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PullImageReply, _impl_.errmsg_)}},
    // string image_ref = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(PullImageReply, _impl_.image_ref_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string image_ref = 1;
    {PROTOBUF_FIELD_OFFSET(PullImageReply, _impl_.image_ref_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string errmsg = 2;
    {PROTOBUF_FIELD_OFFSET(PullImageReply, _impl_.errmsg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\11\6\0\0\0\0\0"
    "image.PullImageReply"
    "image_ref"
    "errmsg"
  }},
};

::uint8_t* PullImageReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:image.PullImageReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string image_ref = 1;
  if (!this->_internal_image_ref().empty()) {
    const std::string& _s = this->_internal_image_ref();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "image.PullImageReply.image_ref");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string errmsg = 2;
  if (!this->_internal_errmsg().empty()) {
    const std::string& _s = this->_internal_errmsg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "image.PullImageReply.errmsg");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:image.PullImageReply)
  return target;
}

::size_t PullImageReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:image.PullImageReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string image_ref = 1;
  if (!this->_internal_image_ref().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_image_ref());
  }

  // string errmsg = 2;
  if (!this->_internal_errmsg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_errmsg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData PullImageReply::_class_data_ = {
    PullImageReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* PullImageReply::GetClassData() const {
  return &_class_data_;
}

void PullImageReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PullImageReply*>(&to_msg);
  auto& from = static_cast<const PullImageReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:image.PullImageReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_image_ref().empty()) {
    _this->_internal_set_image_ref(from._internal_image_ref());
  }
  if (!from._internal_errmsg().empty()) {
    _this->_internal_set_errmsg(from._internal_errmsg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PullImageReply::CopyFrom(const PullImageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:image.PullImageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PullImageReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PullImageReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PullImageReply::InternalSwap(PullImageReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_ref_, &other->_impl_.image_ref_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.errmsg_, &other->_impl_.errmsg_, arena);
}

::google::protobuf::Metadata PullImageReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_image_2eproto_getter, &descriptor_table_image_2eproto_once,
      file_level_metadata_image_2eproto[1]);
}
// ===================================================================

class RemoveImageRequest::_Internal {
 public:
};

RemoveImageRequest::RemoveImageRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:image.RemoveImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE RemoveImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : image_(arena, from.image_),
        _cached_size_{0} {}

RemoveImageRequest::RemoveImageRequest(
    ::google::protobuf::Arena* arena,
    const RemoveImageRequest& from)
    : ::google::protobuf::Message(arena) {
  RemoveImageRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.force_ = from._impl_.force_;

  // @@protoc_insertion_point(copy_constructor:image.RemoveImageRequest)
}
inline PROTOBUF_NDEBUG_INLINE RemoveImageRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : image_(arena),
        _cached_size_{0} {}

inline void RemoveImageRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.force_ = {};
}
RemoveImageRequest::~RemoveImageRequest() {
  // @@protoc_insertion_point(destructor:image.RemoveImageRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RemoveImageRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.image_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RemoveImageRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:image.RemoveImageRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.image_.ClearToEmpty();
  _impl_.force_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RemoveImageRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 38, 2> RemoveImageRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RemoveImageRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool force = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(RemoveImageRequest, _impl_.force_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(RemoveImageRequest, _impl_.force_)}},
    // string image = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RemoveImageRequest, _impl_.image_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string image = 1;
    {PROTOBUF_FIELD_OFFSET(RemoveImageRequest, _impl_.image_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool force = 2;
    {PROTOBUF_FIELD_OFFSET(RemoveImageRequest, _impl_.force_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\30\5\0\0\0\0\0\0"
    "image.RemoveImageRequest"
    "image"
  }},
};

::uint8_t* RemoveImageRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:image.RemoveImageRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string image = 1;
  if (!this->_internal_image().empty()) {
    const std::string& _s = this->_internal_image();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "image.RemoveImageRequest.image");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool force = 2;
  if (this->_internal_force() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_force(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:image.RemoveImageRequest)
  return target;
}

::size_t RemoveImageRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:image.RemoveImageRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string image = 1;
  if (!this->_internal_image().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_image());
  }

  // bool force = 2;
  if (this->_internal_force() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RemoveImageRequest::_class_data_ = {
    RemoveImageRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RemoveImageRequest::GetClassData() const {
  return &_class_data_;
}

void RemoveImageRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RemoveImageRequest*>(&to_msg);
  auto& from = static_cast<const RemoveImageRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:image.RemoveImageRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_image().empty()) {
    _this->_internal_set_image(from._internal_image());
  }
  if (from._internal_force() != 0) {
    _this->_internal_set_force(from._internal_force());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RemoveImageRequest::CopyFrom(const RemoveImageRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:image.RemoveImageRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RemoveImageRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RemoveImageRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RemoveImageRequest::InternalSwap(RemoveImageRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_, &other->_impl_.image_, arena);
        swap(_impl_.force_, other->_impl_.force_);
}

::google::protobuf::Metadata RemoveImageRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_image_2eproto_getter, &descriptor_table_image_2eproto_once,
      file_level_metadata_image_2eproto[2]);
}
// ===================================================================

class RemoveImageReply::_Internal {
 public:
};

RemoveImageReply::RemoveImageReply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:image.RemoveImageReply)
}
inline PROTOBUF_NDEBUG_INLINE RemoveImageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : errmsg_(arena, from.errmsg_),
        _cached_size_{0} {}

RemoveImageReply::RemoveImageReply(
    ::google::protobuf::Arena* arena,
    const RemoveImageReply& from)
    : ::google::protobuf::Message(arena) {
  RemoveImageReply* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:image.RemoveImageReply)
}
inline PROTOBUF_NDEBUG_INLINE RemoveImageReply::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : errmsg_(arena),
        _cached_size_{0} {}

inline void RemoveImageReply::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RemoveImageReply::~RemoveImageReply() {
  // @@protoc_insertion_point(destructor:image.RemoveImageReply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RemoveImageReply::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.errmsg_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RemoveImageReply::Clear() {
// @@protoc_insertion_point(message_clear_start:image.RemoveImageReply)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.errmsg_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RemoveImageReply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 37, 2> RemoveImageReply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RemoveImageReply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string errmsg = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RemoveImageReply, _impl_.errmsg_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string errmsg = 1;
    {PROTOBUF_FIELD_OFFSET(RemoveImageReply, _impl_.errmsg_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\26\6\0\0\0\0\0\0"
    "image.RemoveImageReply"
    "errmsg"
  }},
};

::uint8_t* RemoveImageReply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:image.RemoveImageReply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string errmsg = 1;
  if (!this->_internal_errmsg().empty()) {
    const std::string& _s = this->_internal_errmsg();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "image.RemoveImageReply.errmsg");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:image.RemoveImageReply)
  return target;
}

::size_t RemoveImageReply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:image.RemoveImageReply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string errmsg = 1;
  if (!this->_internal_errmsg().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_errmsg());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RemoveImageReply::_class_data_ = {
    RemoveImageReply::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RemoveImageReply::GetClassData() const {
  return &_class_data_;
}

void RemoveImageReply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RemoveImageReply*>(&to_msg);
  auto& from = static_cast<const RemoveImageReply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:image.RemoveImageReply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_errmsg().empty()) {
    _this->_internal_set_errmsg(from._internal_errmsg());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RemoveImageReply::CopyFrom(const RemoveImageReply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:image.RemoveImageReply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RemoveImageReply::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RemoveImageReply::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RemoveImageReply::InternalSwap(RemoveImageReply* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.errmsg_, &other->_impl_.errmsg_, arena);
}

::google::protobuf::Metadata RemoveImageReply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_image_2eproto_getter, &descriptor_table_image_2eproto_once,
      file_level_metadata_image_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace image
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
